pipeline {
    agent any
    stages {
        stage('Pull code from git') {
            steps {
                git credentialsId: "gitee-user-password", url: "https://gitee.com/maovo/pygo-srvs.git"
            }
        }
        stage('Build project') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: "192.168.200.129",
                            transfers: [
                                sshTransfer(
                                    cleanRemote: false,
                                    excludes: '',
                                    execCommand: 'echo "success"',
                                    remoteDirectory: '/docker/python',
                                    remoteDirectorySDF: false,
                                    removePrefix: '',
                                    sourceFiles: 'order_srv/**'
                                ),
                                sshTransfer(
                                    cleanRemote: false,
                                    excludes: '',
                                    execCommand: 'chmod +x /docker/python/order_srv/start.sh && cd /docker/python/order_srv/ && ./start.sh',
                                    remoteDirectory: '/docker/python',
                                    remoteDirectorySDF: false,
                                    removePrefix: '',
                                    sourceFiles: 'common/**'
                                )
                            ],
                            usePromotionTimestamp: false,
                            useWorkspaceInPromotion: false,
                        )
                    ],
                    continueOnError: false,
                    failOnError: true,
                    alwaysPublishFromMaster: false
                )
            }
        }

    }
}
