# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userfavorite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='userfavorite.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12userfavorite.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n\x13UserFavoriteRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0f\n\x07goodsId\x18\x02 \x01(\x05\"7\n\x14UserFavoriteResponse\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0f\n\x07goodsId\x18\x02 \x01(\x05\"N\n\x18UserFavoriteListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12#\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x15.UserFavoriteResponse2\xa5\x02\n\x0cUserFavorite\x12\x46\n\x13GetUserFavoriteList\x12\x14.UserFavoriteRequest\x1a\x19.UserFavoriteListResponse\x12\x45\n\x15GetUserFavoriteDetail\x12\x14.UserFavoriteRequest\x1a\x16.google.protobuf.Empty\x12\x42\n\x12\x43reateUserFavorite\x12\x14.UserFavoriteRequest\x1a\x16.google.protobuf.Empty\x12\x42\n\x12\x44\x65leteUserFavorite\x12\x14.UserFavoriteRequest\x1a\x16.google.protobuf.EmptyB\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_USERFAVORITEREQUEST = _descriptor.Descriptor(
  name='UserFavoriteRequest',
  full_name='UserFavoriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='UserFavoriteRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goodsId', full_name='UserFavoriteRequest.goodsId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=105,
)


_USERFAVORITERESPONSE = _descriptor.Descriptor(
  name='UserFavoriteResponse',
  full_name='UserFavoriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='UserFavoriteResponse.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goodsId', full_name='UserFavoriteResponse.goodsId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=162,
)


_USERFAVORITELISTRESPONSE = _descriptor.Descriptor(
  name='UserFavoriteListResponse',
  full_name='UserFavoriteListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='UserFavoriteListResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='UserFavoriteListResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=242,
)

_USERFAVORITELISTRESPONSE.fields_by_name['data'].message_type = _USERFAVORITERESPONSE
DESCRIPTOR.message_types_by_name['UserFavoriteRequest'] = _USERFAVORITEREQUEST
DESCRIPTOR.message_types_by_name['UserFavoriteResponse'] = _USERFAVORITERESPONSE
DESCRIPTOR.message_types_by_name['UserFavoriteListResponse'] = _USERFAVORITELISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserFavoriteRequest = _reflection.GeneratedProtocolMessageType('UserFavoriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERFAVORITEREQUEST,
  '__module__' : 'userfavorite_pb2'
  # @@protoc_insertion_point(class_scope:UserFavoriteRequest)
  })
_sym_db.RegisterMessage(UserFavoriteRequest)

UserFavoriteResponse = _reflection.GeneratedProtocolMessageType('UserFavoriteResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERFAVORITERESPONSE,
  '__module__' : 'userfavorite_pb2'
  # @@protoc_insertion_point(class_scope:UserFavoriteResponse)
  })
_sym_db.RegisterMessage(UserFavoriteResponse)

UserFavoriteListResponse = _reflection.GeneratedProtocolMessageType('UserFavoriteListResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERFAVORITELISTRESPONSE,
  '__module__' : 'userfavorite_pb2'
  # @@protoc_insertion_point(class_scope:UserFavoriteListResponse)
  })
_sym_db.RegisterMessage(UserFavoriteListResponse)


DESCRIPTOR._options = None

_USERFAVORITE = _descriptor.ServiceDescriptor(
  name='UserFavorite',
  full_name='UserFavorite',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=245,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserFavoriteList',
    full_name='UserFavorite.GetUserFavoriteList',
    index=0,
    containing_service=None,
    input_type=_USERFAVORITEREQUEST,
    output_type=_USERFAVORITELISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserFavoriteDetail',
    full_name='UserFavorite.GetUserFavoriteDetail',
    index=1,
    containing_service=None,
    input_type=_USERFAVORITEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateUserFavorite',
    full_name='UserFavorite.CreateUserFavorite',
    index=2,
    containing_service=None,
    input_type=_USERFAVORITEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteUserFavorite',
    full_name='UserFavorite.DeleteUserFavorite',
    index=3,
    containing_service=None,
    input_type=_USERFAVORITEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERFAVORITE)

DESCRIPTOR.services_by_name['UserFavorite'] = _USERFAVORITE

# @@protoc_insertion_point(module_scope)
