# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='banner.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62\x61nner.proto\x1a\x1bgoogle/protobuf/empty.proto\"F\n\rBannerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\"G\n\x0e\x42\x61nnerResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\"B\n\x12\x42\x61nnerListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1d\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0f.BannerResponse2\xe4\x01\n\x06\x42\x61nner\x12\x39\n\nBannerList\x12\x16.google.protobuf.Empty\x1a\x13.BannerListResponse\x12/\n\x0c\x43reateBanner\x12\x0e.BannerRequest\x1a\x0f.BannerResponse\x12\x36\n\x0c\x44\x65leteBanner\x12\x0e.BannerRequest\x1a\x16.google.protobuf.Empty\x12\x36\n\x0cUpdateBanner\x12\x0e.BannerRequest\x1a\x16.google.protobuf.EmptyB\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_BANNERREQUEST = _descriptor.Descriptor(
  name='BannerRequest',
  full_name='BannerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BannerRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='BannerRequest.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='BannerRequest.image', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='BannerRequest.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=115,
)


_BANNERRESPONSE = _descriptor.Descriptor(
  name='BannerResponse',
  full_name='BannerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BannerResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='BannerResponse.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='BannerResponse.image', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='BannerResponse.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=188,
)


_BANNERLISTRESPONSE = _descriptor.Descriptor(
  name='BannerListResponse',
  full_name='BannerListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='BannerListResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='BannerListResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=256,
)

_BANNERLISTRESPONSE.fields_by_name['data'].message_type = _BANNERRESPONSE
DESCRIPTOR.message_types_by_name['BannerRequest'] = _BANNERREQUEST
DESCRIPTOR.message_types_by_name['BannerResponse'] = _BANNERRESPONSE
DESCRIPTOR.message_types_by_name['BannerListResponse'] = _BANNERLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BannerRequest = _reflection.GeneratedProtocolMessageType('BannerRequest', (_message.Message,), {
  'DESCRIPTOR' : _BANNERREQUEST,
  '__module__' : 'banner_pb2'
  # @@protoc_insertion_point(class_scope:BannerRequest)
  })
_sym_db.RegisterMessage(BannerRequest)

BannerResponse = _reflection.GeneratedProtocolMessageType('BannerResponse', (_message.Message,), {
  'DESCRIPTOR' : _BANNERRESPONSE,
  '__module__' : 'banner_pb2'
  # @@protoc_insertion_point(class_scope:BannerResponse)
  })
_sym_db.RegisterMessage(BannerResponse)

BannerListResponse = _reflection.GeneratedProtocolMessageType('BannerListResponse', (_message.Message,), {
  'DESCRIPTOR' : _BANNERLISTRESPONSE,
  '__module__' : 'banner_pb2'
  # @@protoc_insertion_point(class_scope:BannerListResponse)
  })
_sym_db.RegisterMessage(BannerListResponse)


DESCRIPTOR._options = None

_BANNER = _descriptor.ServiceDescriptor(
  name='Banner',
  full_name='Banner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=259,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='BannerList',
    full_name='Banner.BannerList',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BANNERLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateBanner',
    full_name='Banner.CreateBanner',
    index=1,
    containing_service=None,
    input_type=_BANNERREQUEST,
    output_type=_BANNERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteBanner',
    full_name='Banner.DeleteBanner',
    index=2,
    containing_service=None,
    input_type=_BANNERREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBanner',
    full_name='Banner.UpdateBanner',
    index=3,
    containing_service=None,
    input_type=_BANNERREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANNER)

DESCRIPTOR.services_by_name['Banner'] = _BANNER

# @@protoc_insertion_point(module_scope)
