# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import banner_pb2 as banner__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BannerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BannerList = channel.unary_unary(
                '/Banner/BannerList',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=banner__pb2.BannerListResponse.FromString,
                )
        self.CreateBanner = channel.unary_unary(
                '/Banner/CreateBanner',
                request_serializer=banner__pb2.BannerRequest.SerializeToString,
                response_deserializer=banner__pb2.BannerResponse.FromString,
                )
        self.DeleteBanner = channel.unary_unary(
                '/Banner/DeleteBanner',
                request_serializer=banner__pb2.BannerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.UpdateBanner = channel.unary_unary(
                '/Banner/UpdateBanner',
                request_serializer=banner__pb2.BannerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class BannerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BannerList(self, request, context):
        """轮播图接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BannerList': grpc.unary_unary_rpc_method_handler(
                    servicer.BannerList,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=banner__pb2.BannerListResponse.SerializeToString,
            ),
            'CreateBanner': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBanner,
                    request_deserializer=banner__pb2.BannerRequest.FromString,
                    response_serializer=banner__pb2.BannerResponse.SerializeToString,
            ),
            'DeleteBanner': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBanner,
                    request_deserializer=banner__pb2.BannerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateBanner': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBanner,
                    request_deserializer=banner__pb2.BannerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Banner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Banner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BannerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Banner/BannerList',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            banner__pb2.BannerListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Banner/CreateBanner',
            banner__pb2.BannerRequest.SerializeToString,
            banner__pb2.BannerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Banner/DeleteBanner',
            banner__pb2.BannerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Banner/UpdateBanner',
            banner__pb2.BannerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
