# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: category.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='category.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63\x61tegory.proto\x1a\x1bgoogle/protobuf/empty.proto\"0\n\x13\x43\x61tegoryListRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\"e\n\x13\x43\x61tegoryInfoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0eparentCategory\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\r\n\x05isTab\x18\x05 \x01(\x08\"#\n\x15\x44\x65leteCategoryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"f\n\x14\x43\x61tegoryInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0eparentCategory\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\x12\r\n\x05isTab\x18\x05 \x01(\x08\"\\\n\x14\x43\x61tegoryListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12#\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x15.CategoryInfoResponse\x12\x10\n\x08jsonData\x18\x03 \x01(\t\"z\n\x17SubCategoryListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12#\n\x04info\x18\x02 \x01(\x0b\x32\x15.CategoryInfoResponse\x12+\n\x0csubCategorys\x18\x03 \x03(\x0b\x32\x15.CategoryInfoResponse2\xd3\x02\n\x08\x43\x61tegory\x12\x44\n\x13GetAllCategorysList\x12\x16.google.protobuf.Empty\x1a\x15.CategoryListResponse\x12@\n\x0eGetSubCategory\x12\x14.CategoryListRequest\x1a\x18.SubCategoryListResponse\x12=\n\x0e\x43reateCategory\x12\x14.CategoryInfoRequest\x1a\x15.CategoryInfoResponse\x12@\n\x0e\x44\x65leteCategory\x12\x16.DeleteCategoryRequest\x1a\x16.google.protobuf.Empty\x12>\n\x0eUpdateCategory\x12\x14.CategoryInfoRequest\x1a\x16.google.protobuf.EmptyB\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_CATEGORYLISTREQUEST = _descriptor.Descriptor(
  name='CategoryListRequest',
  full_name='CategoryListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CategoryListRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='CategoryListRequest.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=95,
)


_CATEGORYINFOREQUEST = _descriptor.Descriptor(
  name='CategoryInfoRequest',
  full_name='CategoryInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CategoryInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='CategoryInfoRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parentCategory', full_name='CategoryInfoRequest.parentCategory', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='CategoryInfoRequest.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isTab', full_name='CategoryInfoRequest.isTab', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=198,
)


_DELETECATEGORYREQUEST = _descriptor.Descriptor(
  name='DeleteCategoryRequest',
  full_name='DeleteCategoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeleteCategoryRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=235,
)


_CATEGORYINFORESPONSE = _descriptor.Descriptor(
  name='CategoryInfoResponse',
  full_name='CategoryInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CategoryInfoResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='CategoryInfoResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parentCategory', full_name='CategoryInfoResponse.parentCategory', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='CategoryInfoResponse.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isTab', full_name='CategoryInfoResponse.isTab', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=339,
)


_CATEGORYLISTRESPONSE = _descriptor.Descriptor(
  name='CategoryListResponse',
  full_name='CategoryListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='CategoryListResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='CategoryListResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='CategoryListResponse.jsonData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=433,
)


_SUBCATEGORYLISTRESPONSE = _descriptor.Descriptor(
  name='SubCategoryListResponse',
  full_name='SubCategoryListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='SubCategoryListResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='SubCategoryListResponse.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subCategorys', full_name='SubCategoryListResponse.subCategorys', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=557,
)

_CATEGORYLISTRESPONSE.fields_by_name['data'].message_type = _CATEGORYINFORESPONSE
_SUBCATEGORYLISTRESPONSE.fields_by_name['info'].message_type = _CATEGORYINFORESPONSE
_SUBCATEGORYLISTRESPONSE.fields_by_name['subCategorys'].message_type = _CATEGORYINFORESPONSE
DESCRIPTOR.message_types_by_name['CategoryListRequest'] = _CATEGORYLISTREQUEST
DESCRIPTOR.message_types_by_name['CategoryInfoRequest'] = _CATEGORYINFOREQUEST
DESCRIPTOR.message_types_by_name['DeleteCategoryRequest'] = _DELETECATEGORYREQUEST
DESCRIPTOR.message_types_by_name['CategoryInfoResponse'] = _CATEGORYINFORESPONSE
DESCRIPTOR.message_types_by_name['CategoryListResponse'] = _CATEGORYLISTRESPONSE
DESCRIPTOR.message_types_by_name['SubCategoryListResponse'] = _SUBCATEGORYLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryListRequest = _reflection.GeneratedProtocolMessageType('CategoryListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYLISTREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:CategoryListRequest)
  })
_sym_db.RegisterMessage(CategoryListRequest)

CategoryInfoRequest = _reflection.GeneratedProtocolMessageType('CategoryInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYINFOREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:CategoryInfoRequest)
  })
_sym_db.RegisterMessage(CategoryInfoRequest)

DeleteCategoryRequest = _reflection.GeneratedProtocolMessageType('DeleteCategoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETECATEGORYREQUEST,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:DeleteCategoryRequest)
  })
_sym_db.RegisterMessage(DeleteCategoryRequest)

CategoryInfoResponse = _reflection.GeneratedProtocolMessageType('CategoryInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYINFORESPONSE,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:CategoryInfoResponse)
  })
_sym_db.RegisterMessage(CategoryInfoResponse)

CategoryListResponse = _reflection.GeneratedProtocolMessageType('CategoryListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYLISTRESPONSE,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:CategoryListResponse)
  })
_sym_db.RegisterMessage(CategoryListResponse)

SubCategoryListResponse = _reflection.GeneratedProtocolMessageType('SubCategoryListResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBCATEGORYLISTRESPONSE,
  '__module__' : 'category_pb2'
  # @@protoc_insertion_point(class_scope:SubCategoryListResponse)
  })
_sym_db.RegisterMessage(SubCategoryListResponse)


DESCRIPTOR._options = None

_CATEGORY = _descriptor.ServiceDescriptor(
  name='Category',
  full_name='Category',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=560,
  serialized_end=899,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllCategorysList',
    full_name='Category.GetAllCategorysList',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CATEGORYLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSubCategory',
    full_name='Category.GetSubCategory',
    index=1,
    containing_service=None,
    input_type=_CATEGORYLISTREQUEST,
    output_type=_SUBCATEGORYLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateCategory',
    full_name='Category.CreateCategory',
    index=2,
    containing_service=None,
    input_type=_CATEGORYINFOREQUEST,
    output_type=_CATEGORYINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteCategory',
    full_name='Category.DeleteCategory',
    index=3,
    containing_service=None,
    input_type=_DELETECATEGORYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateCategory',
    full_name='Category.UpdateCategory',
    index=4,
    containing_service=None,
    input_type=_CATEGORYINFOREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CATEGORY)

DESCRIPTOR.services_by_name['Category'] = _CATEGORY

# @@protoc_insertion_point(module_scope)
